[package]
name = "onebbq"
version = "0.1.0"
edition = "2024"

[toolchain]
channel = "nightly"


[profile.release]
lto = "fat"
codegen-units = 1
opt-level=3
panic = "abort"
debug = true
target-cpu = "native"
[dependencies]
libc = "0.2.182"
