[package]
name = "onebbq"
version = "0.1.0"
edition = "2024"

[toolchain]
channel = "nightly"


[profile.release]
lto = "fat"
panic = "abort"
debug = true
target-cpu = "native"
[dependencies]
libc = "0.2.182"